from modules.root_cause_analysis.root_cause_ui import render_root_cause_tab
# ...
tab1, tab2, tab3 = st.tabs(["Detection", "Spread Prediction", "Root Cause"])
# ...
with tab3:
    render_root_cause_tab()
